[project]
name = "dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipywidgets>=8.1.7",
    "matplotlib>=3.9.4",
    "optuna>=4.5.0",
    "scikit-learn>=1.6.1",
]
